services:
  - type: web
    name: smart-tour-ai-backend
    env: node
    region: singapore
    buildCommand: cd backend && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
